name: CI/CD Pipeline

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  NODE_VERSION: '20'
  NPM_VERSION: '10'

jobs:
  # Pre-deployment tests and checks
  test:
    name: Test and Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --force

      - name: Type check
        run: npm run type-check

      - name: Lint
        run: npm run lint

      - name: Run unit tests
        run: npm run test

      - name: Build application
        run: npm run build

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: test-results/
          retention-days: 7

  # Deploy to Vercel (only on master branch)
  deploy:
    name: Deploy to Vercel
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug Vercel Configuration
        run: |
          echo "Checking Vercel configuration..."
          echo "ORG_ID length: ${#VERCEL_ORG_ID}"
          echo "PROJECT_ID length: ${#VERCEL_PROJECT_ID}"
          echo "ORG_ID starts with: ${VERCEL_ORG_ID:0:10}..."
          echo "PROJECT_ID starts with: ${VERCEL_PROJECT_ID:0:10}..."
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-args: '--prod'

      - name: Get deployment URL
        id: deployment-url
        run: |
          # Extract deployment URL from Vercel output
          DEPLOYMENT_URL=$(echo "${{ steps.deploy.outputs.preview-url }}" | sed 's/https:\/\///')
          echo "deployment_url=$DEPLOYMENT_URL" >> $GITHUB_OUTPUT
          echo "full_url=https://$DEPLOYMENT_URL" >> $GITHUB_OUTPUT

      - name: Wait for deployment
        run: |
          echo "Waiting for deployment to be ready..."
          sleep 30

  # Post-deployment E2E tests
  e2e-tests:
    name: E2E Tests (Live Environment)
    runs-on: ubuntu-latest
    needs: deploy
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --force

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run E2E tests against live environment
        run: |
          # Set the base URL to the live deployment
          npx playwright test --base-url=https://${{ needs.deploy.outputs.preview-url }}
        env:
          # Add any environment variables needed for E2E tests
          NODE_ENV: production

      - name: Upload E2E test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: e2e-test-results
          path: |
            test-results/
            playwright-report/
          retention-days: 7

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 7

  # Security and dependency checks
  security:
    name: Security Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --force

      - name: Run security audit
        run: npm audit --audit-level=moderate

      - name: Check for outdated dependencies
        run: npm outdated || true
